baseURL = "https://leosauvage.co"
defaultContentLanguage = "en"
languageCode = "en"
theme = "hugoloveit"
title = "leosauvage.co | Leo Sauvage"
[Permalinks]
posts = ":filename"
[author]
email = ""
link = ""
name = "Leo Sauvage"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 6
startLevel = 2
[mediaTypes."text/plain"]
suffixes = ["md"]
[[menu.main]]
name = "Ingredients"
url = "/ingredients/"
weight = 4
[[menu.main]]
name = "Testing"
url = "/testing/"
weight = 3
[[menu.main]]
name = "Skincare"
url = "/skincare/"
weight = 2
[[menu.main]]
identifier = "posts"
name = "Home"
post = ""
pre = ""
title = ""
url = "/home/"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
post = ""
pre = ""
title = ""
url = "/about/"
weight = 5
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/plain"
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
[params]
dateFormat = "2006-01-02"
defaultTheme = "light"
description = "This is My New Hugo Site"
fingerprint = ""
gitRepo = ""
images = ["/logo.png"]
keywords = ["Theme", "Hugo"]
version = "0.2.X"
[params.analytics]
enable = true
[params.analytics.fathom]
id = ""
server = ""
[params.analytics.google]
anonymizeIP = true
id = "G-47NW8D8FXD"
[params.app]
iconColor = "#5bbad5"
noFavicon = false
svgFavicon = ""
themeColor = "#ffffff"
tileColor = "#da532c"
title = ""
[params.cdn]
data = ""
[params.compatibility]
objectFit = false
polyfill = false
[params.cookieconsent]
enable = false
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""
[params.footer]
author = true
copyright = true
custom = ""
enable = true
hugo = false
icp = ""
license = "<a rel=\"license external nofollow noopener noreffer\" href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\">CC BY-NC 4.0</a>"
since = 2021
[params.header]
desktopMode = "fixed"
mobileMode = "auto"
[params.header.title]
logo = ""
name = "leosauvage.co"
post = ""
pre = "<i class='far fa-kiss-wink-heart fa-fw'></i>"
typeit = false
[params.home]
rss = 10
[params.home.posts]
defaultHiddenFromHomePage = false
enable = true
paginate = 6
[params.home.profile]
avatarURL = "/images/leo.jpeg"
disclaimer = ""
enable = true
gravatarEmail = ""
social = true
subtitle = "This is My New Hugo Site"
title = ""
typeit = true
[params.list]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.page]
fontawesome = true
fraction = false
hiddenFromHomePage = false
hiddenFromSearch = false
lightgallery = false
linkToMarkdown = false
rssFullText = false
ruby = false
twemoji = false
[params.page.code]
copy = true
maxShownLines = 10
[params.page.comment]
enable = false
[params.page.comment.commento]
enable = false
[params.page.comment.disqus]
enable = false
shortname = ""
[params.page.comment.facebook]
appId = ""
enable = false
languageCode = ""
numPosts = 10
width = "100%"
[params.page.comment.gitalk]
clientId = ""
clientSecret = ""
enable = false
owner = ""
repo = ""
[params.page.comment.telegram]
color = ""
colorful = true
dislikes = false
enable = false
height = ""
limit = 5
outlined = false
siteID = ""
[params.page.comment.utterances]
darkTheme = "github-dark"
enable = false
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
repo = ""
[params.page.comment.valine]
appId = ""
appKey = ""
avatar = "mp"
emoji = ""
enable = false
enableQQ = false
highlight = true
lang = ""
meta = ""
pageSize = 10
placeholder = ""
recordIP = true
serverURLs = ""
visitor = true
[params.page.library.css]
[params.page.library.js]
[params.page.mapbox]
accessToken = ""
darkStyle = "mapbox://styles/mapbox/dark-v9"
fullscreen = true
geolocate = true
lightStyle = "mapbox://styles/mapbox/light-v9"
navigation = true
scale = true
[params.page.math]
blockLeftDelimiter = ""
blockRightDelimiter = ""
copyTex = true
enable = false
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
mhchem = true
[params.page.seo]
images = []
[params.page.seo.publisher]
logoUrl = "/images/leo.jpeg"
name = "Leo Sauvage"
[params.page.share]
Baidu = false
Blogger = false
Buffer = false
Digg = false
Evernote = false
Facebook = true
Flipboard = false
HackerNews = false
Instapaper = false
Line = false
Linkedin = true
Mix = false
Myspace = false
Odnoklassniki = false
Pinterest = false
Pocket = false
Reddit = true
Renren = false
Skype = false
Stumbleupon = false
Trello = false
Tumblr = false
Twitter = true
VK = false
Weibo = false
Whatsapp = false
Xing = false
enable = true
[params.page.toc]
auto = true
enable = true
keepStatic = false
[params.search]
absoluteURL = false
contentLength = 4000
enable = true
highlightTag = "em"
maxResultLength = 10
placeholder = ""
snippetLength = 30
type = "lunr"
[params.search.algolia]
appID = ""
index = ""
searchKey = ""
[params.section]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.seo]
image = ""
thumbnailUrl = ""
[params.social]
Angellist = ""
Bandcamp = ""
Behance = ""
Bilibili = ""
Bitbucket = ""
Codepen = ""
Deviantart = ""
Devto = ""
Douban = ""
Dribbble = ""
Email = ""
Facebook = ""
Fivehundredpx = ""
Flickr = ""
Foursquare = ""
FreeCodeCamp = ""
GitHub = ""
Gitea = ""
Gitlab = ""
Goodreads = ""
Googlescholar = ""
Hackernews = ""
Instagram = ""
Jsfiddle = ""
Keybase = ""
Kickstarter = ""
Lastfm = ""
Linkedin = "eleonorecodjosauvage"
Mastodon = ""
Matrix = ""
Medium = ""
Mix = ""
Odnoklassniki = ""
Patreon = ""
Paypal = ""
Pinterest = ""
Quora = ""
RSS = false
Reddit = ""
Researchgate = ""
Skype = ""
Slidershare = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Stackoverflow = ""
Steam = ""
Strava = ""
Telegram = ""
Thingiverse = ""
Tumblr = ""
Twitch = ""
Twitter = "LeoSauvage"
VK = ""
Vine = ""
Weibo = ""
Whatsapp = ""
Wordpress = ""
XMPP = ""
Xing = ""
Youtubechannel = ""
Youtubecustom = ""
Youtubelegacy = ""
Zhihu = ""
[params.typeit]
cursorChar = "|"
cursorSpeed = 1000
duration = -1
speed = 100
[params.verification]
baidu = ""
bing = ""
google = ""
pinterest = ""
yandex = ""
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
